import type { ColorBucket } from "./types";

/** Token → single canonical bucket. Extend here; every token maps to exactly one bucket. */
export const COLOR_TOKEN_ALIASES: Record<string, ColorBucket> = {
  // black
  black: "black",
  noir: "black",
  schwarz: "black",
  nero: "black",
  negro: "black",
  jet: "black",
  onyx: "black",
  ink: "black",
  charcoal: "grey",
  anthracite: "black",
  ebony: "black",
  coal: "black",
  midnight: "black",
  raven: "black",
  graphite: "grey",
  // white
  white: "white",
  blanc: "white",
  weiss: "white",
  bianco: "white",
  blanco: "white",
  ivory: "white",
  cream: "white",
  ecru: "white",
  offwhite: "white",
  snow: "white",
  chalk: "white",
  eggshell: "white",
  champagne: "beige",
  // grey
  grey: "grey",
  gray: "grey",
  gris: "grey",
  grau: "grey",
  heather: "grey",
  ash: "grey",
  slate: "grey",
  stone: "grey",
  smoke: "grey",
  // beige
  beige: "beige",
  sand: "beige",
  tan: "beige",
  khaki: "beige",
  camel: "beige",
  taupe: "beige",
  oat: "beige",
  oatmeal: "beige",
  nude: "beige",
  natural: "beige",
  buff: "beige",
  latte: "beige",
  // brown
  brown: "brown",
  marron: "brown",
  brun: "brown",
  chocolate: "brown",
  coffee: "brown",
  mocha: "brown",
  espresso: "brown",
  cognac: "brown",
  chestnut: "brown",
  walnut: "brown",
  rust: "brown",
  mahogany: "brown",
  // navy
  navy: "navy",
  marine: "navy",
  navyblue: "navy",
  midnightblue: "navy",
  indigo: "navy",
  // blue
  blue: "blue",
  bleu: "blue",
  blau: "blue",
  azul: "blue",
  azure: "blue",
  cobalt: "blue",
  royal: "blue",
  sky: "blue",
  skyblue: "blue",
  iceblue: "blue",
  petrol: "blue",
  teal: "green",
  // green
  green: "green",
  vert: "green",
  grun: "green",
  verde: "green",
  sage: "green",
  forest: "green",
  emerald: "green",
  mint: "green",
  khakigreen: "green",
  pine: "green",
  // olive
  olive: "olive",
  army: "olive",
  military: "olive",
  moss: "olive",
  // red
  red: "red",
  rouge: "red",
  rot: "red",
  rosso: "red",
  rojo: "red",
  crimson: "red",
  scarlet: "red",
  cherry: "red",
  // burgundy
  burgundy: "burgundy",
  bordeaux: "burgundy",
  maroon: "burgundy",
  wine: "burgundy",
  oxblood: "burgundy",
  // pink
  pink: "pink",
  rose: "pink",
  rosa: "pink",
  blush: "pink",
  fuchsia: "pink",
  salmon: "pink",
  coral: "pink",
  // purple
  purple: "purple",
  violet: "purple",
  lilac: "purple",
  lavender: "purple",
  plum: "purple",
  mauve: "purple",
  // orange
  orange: "orange",
  tangerine: "orange",
  apricot: "orange",
  peach: "orange",
  terracotta: "orange",
  // yellow
  yellow: "yellow",
  jaune: "yellow",
  gelb: "yellow",
  mustard: "yellow",
  lemon: "yellow",
  ochre: "yellow",
  // gold / silver
  gold: "gold",
  golden: "gold",
  silver: "silver",
  metallic: "silver",
  chrome: "silver",
  // denim / multi / print
  denim: "denim",
  jean: "denim",
  jeans: "denim",
  washed: "denim",
  multi: "multi",
  multicolor: "multi",
  multicolour: "multi",
  assorted: "multi",
  rainbow: "multi",
  print: "print",
  printed: "print",
  floral: "print",
  striped: "print",
  stripe: "print",
  check: "print",
  checked: "print",
  plaid: "print",
  camo: "print",
  camouflage: "print",
  leopard: "print",
  graphic: "print",
  pattern: "print",
  patterned: "print",
};

export const COLOR_MODIFIERS = new Set([
  "washed",
  "dark",
  "light",
  "deep",
  "pale",
  "dusty",
  "faded",
  "vintage",
  "heather",
  "bright",
  "soft",
  "matte",
  "night",
]);

export const TWO_TOKEN_COLOR_OVERRIDES: Array<{
  pattern: RegExp;
  bucket: ColorBucket;
}> = [
  { pattern: /\bmidnight\s+blue\b/, bucket: "navy" },
  { pattern: /\boff\s+white\b/, bucket: "white" },
  { pattern: /\bnavy\s+blue\b/, bucket: "navy" },
  { pattern: /\blight\s+blue\b/, bucket: "blue" },
  { pattern: /\bbaby\s+blue\b/, bucket: "blue" },
  { pattern: /\bdark\s+green\b/, bucket: "green" },
  { pattern: /\barmy\s+green\b/, bucket: "olive" },
  { pattern: /\brose\s+gold\b/, bucket: "gold" },
  { pattern: /\bsand\s+beige\b/, bucket: "beige" },
];
