/**
 * In-house onboarding style catalog for worn / aspirational grids.
 * Curated STYLE list — not Shopify. Looks are mode-agnostic:
 * worn vs wanted is decided by the quiz step + ranker, not by the asset.
 * Photos: public/onboarding/outfits/{id}.png → imageUrl "/onboarding/outfits/{id}.png"
 */

import type { CastingArchetype } from "./outfit-grid-matrix";
import type { StyleEraValue } from "./form-options";

export type OutfitGenderBucket =
  | "feminine"
  | "masculine"
  | "androgynous"
  | "any";

export type OutfitFormality = "casual" | "smart" | "formal" | "athletic";

export type OutfitStyleLook = {
  id: string;
  /** Absolute or same-origin. Prefer /onboarding/outfits/{id}.png */
  imageUrl: string;
  genders: OutfitGenderBucket[];
  /**
   * Empty = all eras.
   * Use style-era values from form-options (e.g. "23_29", "30s").
   */
  eras: StyleEraValue[];
  /** Primary first — used for matrix cell fill. */
  archetypes: CastingArchetype[];
  label: string;
  title?: string;
  tasteTags: string[];
  /** Empty = any lifestyle. Values like campus_life, deep_in_career. */
  lifestyles: string[];
  /** Empty = any spend. best_value | premium | luxury | deal_hunter | design_first. */
  spend: string[];
  formality: OutfitFormality;
  colorFamily: string;
};

/**
 * Put generated photos in either:
 *   public/onboarding/outfits/{id}.png  (served at /onboarding/outfits/{id}.png)
 * or copy from src/lib/onboarding/outfits/ (source of generated assets).
 * Prefer local paths via outfitPhotoUrl(id).
 */
export const OUTFIT_PHOTO_PUBLIC_DIR = "public/onboarding/outfits";
export const OUTFIT_PHOTO_URL_PREFIX = "/onboarding/outfits";

export function outfitPhotoUrl(
  id: string,
  ext: "webp" | "jpg" | "png" = "png",
) {
  return `${OUTFIT_PHOTO_URL_PREFIX}/${id}.${ext}`;
}

/** Catalog images: local PNGs in /public/onboarding/outfits/. */
const photo = (id: string) => outfitPhotoUrl(id, "png");

/**
 * Seed style library. Same look can appear as worn for one user and wanted for another.
 */
export const INHOUSE_OUTFIT_LOOKS: OutfitStyleLook[] = [
  // ── Feminine ──────────────────────────────────────────────
  {
    id: "f-w-parisian-01",
    imageUrl: photo("f-w-parisian-01"),
    genders: ["feminine"],
    eras: ["23_29", "30s", "40s"],
    archetypes: ["Parisian"],
    label: "trench + café knit",
    tasteTags: ["trench", "knit", "parisian", "neutral"],
    lifestyles: ["deep_in_career", "first_job"],
    spend: ["premium", "design_first", "best_value"],
    formality: "smart",
    colorFamily: "camel",
  },
  {
    id: "f-w-minimal-01",
    imageUrl: photo("f-w-minimal-01"),
    genders: ["feminine"],
    eras: ["18_22", "23_29", "30s", "40s"],
    archetypes: ["Minimal"],
    label: "black column day",
    tasteTags: ["black", "column", "minimal", "clean"],
    lifestyles: [],
    spend: ["premium", "best_value", "design_first"],
    formality: "smart",
    colorFamily: "black",
  },
  {
    id: "f-w-romantic-01",
    imageUrl: photo("f-w-romantic-01"),
    genders: ["feminine"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Romantic"],
    label: "soft blouse + midi",
    tasteTags: ["blouse", "midi", "romantic", "soft"],
    lifestyles: [],
    spend: ["best_value", "premium"],
    formality: "smart",
    colorFamily: "blush",
  },
  {
    id: "f-w-street-01",
    imageUrl: photo("f-w-street-01"),
    genders: ["feminine", "androgynous"],
    eras: ["15_17", "18_22", "23_29", "30s"],
    archetypes: ["Street"],
    label: "denim + white sneaks",
    tasteTags: ["denim", "sneakers", "street", "casual"],
    lifestyles: ["campus_life", "first_job"],
    spend: ["best_value", "deal_hunter", "design_first"],
    formality: "casual",
    colorFamily: "indigo",
  },
  {
    id: "f-w-classic-01",
    imageUrl: photo("f-w-classic-01"),
    genders: ["feminine"],
    eras: ["23_29", "30s", "40s", "50s_60s"],
    archetypes: ["Classic"],
    label: "blazer + trousers",
    tasteTags: ["blazer", "trousers", "classic", "work"],
    lifestyles: ["deep_in_career", "running_the_show", "first_job"],
    spend: ["premium", "luxury", "best_value"],
    formality: "smart",
    colorFamily: "navy",
  },
  {
    id: "f-w-sporty-01",
    imageUrl: photo("f-w-sporty-01"),
    genders: ["feminine", "androgynous"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Sporty"],
    label: "knit + easy joggers",
    tasteTags: ["knit", "joggers", "sporty", "athleisure"],
    lifestyles: ["kids_in_the_mix", "time_is_mine", "campus_life"],
    spend: ["best_value", "deal_hunter"],
    formality: "athletic",
    colorFamily: "grey",
  },
  {
    id: "f-w-boho-01",
    imageUrl: photo("f-w-boho-01"),
    genders: ["feminine"],
    eras: ["18_22", "23_29", "30s", "40s"],
    archetypes: ["Boho"],
    label: "linen shirt set",
    tasteTags: ["linen", "relaxed", "boho", "earth"],
    lifestyles: ["time_is_mine"],
    spend: ["best_value", "design_first", "premium"],
    formality: "casual",
    colorFamily: "sand",
  },
  {
    id: "f-w-bold-01",
    imageUrl: photo("f-w-bold-01"),
    genders: ["feminine"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Bold"],
    label: "leather + graphic tee",
    tasteTags: ["leather", "graphic", "bold", "edge"],
    lifestyles: [],
    spend: ["design_first", "premium", "best_value"],
    formality: "casual",
    colorFamily: "black",
  },
  {
    id: "f-w-wild-01",
    imageUrl: photo("f-w-wild-01"),
    genders: ["feminine"],
    eras: [],
    archetypes: ["Wildcard"],
    label: "hoodie + leggings truth",
    tasteTags: ["hoodie", "leggings", "comfort", "real"],
    lifestyles: ["kids_in_the_mix", "time_is_mine", "campus_life"],
    spend: ["best_value", "deal_hunter"],
    formality: "casual",
    colorFamily: "grey",
  },

  // ── Feminine (elevated / dressier options in library) ─────────────────────────────────────
  {
    id: "f-a-parisian-01",
    imageUrl: photo("f-a-parisian-01"),
    genders: ["feminine"],
    eras: ["23_29", "30s", "40s"],
    archetypes: ["Parisian"],
    label: "quiet-luxury airport",
    tasteTags: ["cashmere", "travel", "quiet-luxury", "parisian"],
    lifestyles: ["deep_in_career", "running_the_show"],
    spend: ["luxury", "premium", "design_first"],
    formality: "smart",
    colorFamily: "cream",
  },
  {
    id: "f-a-minimal-01",
    imageUrl: photo("f-a-minimal-01"),
    genders: ["feminine"],
    eras: ["23_29", "30s", "40s", "50s_60s"],
    archetypes: ["Minimal"],
    label: "gallery black column",
    tasteTags: ["gallery", "black", "minimal", "sculptural"],
    lifestyles: [],
    spend: ["luxury", "premium", "design_first"],
    formality: "formal",
    colorFamily: "black",
  },
  {
    id: "f-a-romantic-01",
    imageUrl: photo("f-a-romantic-01"),
    genders: ["feminine"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Romantic"],
    label: "garden party dress",
    tasteTags: ["garden", "dress", "romantic", "occasion"],
    lifestyles: [],
    spend: ["premium", "luxury", "design_first"],
    formality: "formal",
    colorFamily: "floral",
  },
  {
    id: "f-a-street-01",
    imageUrl: photo("f-a-street-01"),
    genders: ["feminine", "androgynous"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Street"],
    label: "street-sharp night",
    tasteTags: ["street", "leather", "sharp", "night"],
    lifestyles: [],
    spend: ["premium", "design_first", "luxury"],
    formality: "smart",
    colorFamily: "black",
  },
  {
    id: "f-a-classic-01",
    imageUrl: photo("f-a-classic-01"),
    genders: ["feminine"],
    eras: ["30s", "40s", "50s_60s", "65_plus"],
    archetypes: ["Classic"],
    label: "tailored suit day",
    tasteTags: ["suit", "tailored", "classic", "power"],
    lifestyles: ["deep_in_career", "running_the_show"],
    spend: ["luxury", "premium"],
    formality: "formal",
    colorFamily: "charcoal",
  },
  {
    id: "f-a-sporty-01",
    imageUrl: photo("f-a-sporty-01"),
    genders: ["feminine"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Sporty"],
    label: "clean matching set",
    tasteTags: ["athleisure", "clean", "sporty", "elevated"],
    lifestyles: [],
    spend: ["premium", "design_first", "best_value"],
    formality: "athletic",
    colorFamily: "cream",
  },
  {
    id: "f-a-boho-01",
    imageUrl: photo("f-a-boho-01"),
    genders: ["feminine"],
    eras: ["18_22", "23_29", "30s", "40s"],
    archetypes: ["Boho"],
    label: "festival layers",
    tasteTags: ["boho", "festival", "layers", "print"],
    lifestyles: ["time_is_mine"],
    spend: ["design_first", "premium", "best_value"],
    formality: "casual",
    colorFamily: "earth",
  },
  {
    id: "f-a-bold-01",
    imageUrl: photo("f-a-bold-01"),
    genders: ["feminine"],
    eras: ["23_29", "30s", "40s"],
    archetypes: ["Bold"],
    label: "sequin evening hit",
    tasteTags: ["sequin", "evening", "bold", "glam"],
    lifestyles: [],
    spend: ["luxury", "premium", "design_first"],
    formality: "formal",
    colorFamily: "gold",
  },
  {
    id: "f-a-wild-01",
    imageUrl: photo("f-a-wild-01"),
    genders: ["feminine"],
    eras: [],
    archetypes: ["Wildcard"],
    label: "architect coat moment",
    tasteTags: ["coat", "statement", "sculptural", "stretch"],
    lifestyles: [],
    spend: ["luxury", "design_first", "premium"],
    formality: "smart",
    colorFamily: "ivory",
  },

  // ── Masculine ────────────────────────────────────────────
  {
    id: "m-w-parisian-01",
    imageUrl: photo("m-w-parisian-01"),
    genders: ["masculine"],
    eras: ["23_29", "30s", "40s"],
    archetypes: ["Parisian"],
    label: "trench + knit polo",
    tasteTags: ["trench", "polo", "parisian", "smart"],
    lifestyles: ["deep_in_career", "first_job"],
    spend: ["premium", "best_value"],
    formality: "smart",
    colorFamily: "camel",
  },
  {
    id: "m-w-minimal-01",
    imageUrl: photo("m-w-minimal-01"),
    genders: ["masculine", "androgynous"],
    eras: [],
    archetypes: ["Minimal"],
    label: "black tee + clean pants",
    tasteTags: ["black", "tee", "minimal", "clean"],
    lifestyles: [],
    spend: ["best_value", "premium", "design_first"],
    formality: "casual",
    colorFamily: "black",
  },
  {
    id: "m-w-romantic-01",
    imageUrl: photo("m-w-romantic-01"),
    genders: ["masculine"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Romantic"],
    label: "soft oxford + chinos",
    tasteTags: ["oxford", "chinos", "soft", "romantic"],
    lifestyles: [],
    spend: ["best_value", "premium"],
    formality: "smart",
    colorFamily: "blue",
  },
  {
    id: "m-w-street-01",
    imageUrl: photo("m-w-street-01"),
    genders: ["masculine", "androgynous"],
    eras: ["15_17", "18_22", "23_29", "30s"],
    archetypes: ["Street"],
    label: "denim on denim",
    tasteTags: ["denim", "jeans", "street", "sneakers"],
    lifestyles: ["campus_life", "first_job"],
    spend: ["best_value", "deal_hunter", "design_first"],
    formality: "casual",
    colorFamily: "indigo",
  },
  {
    id: "m-w-classic-01",
    imageUrl: photo("m-w-classic-01"),
    genders: ["masculine"],
    eras: ["23_29", "30s", "40s", "50s_60s", "65_plus"],
    archetypes: ["Classic"],
    label: "blazer + chinos day",
    tasteTags: ["blazer", "chinos", "classic", "work"],
    lifestyles: ["deep_in_career", "running_the_show"],
    spend: ["premium", "luxury", "best_value"],
    formality: "smart",
    colorFamily: "navy",
  },
  {
    id: "m-w-sporty-01",
    imageUrl: photo("m-w-sporty-01"),
    genders: ["masculine"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Sporty"],
    label: "hoodie + joggers",
    tasteTags: ["hoodie", "joggers", "sporty", "athleisure"],
    lifestyles: ["kids_in_the_mix", "campus_life", "time_is_mine"],
    spend: ["best_value", "deal_hunter"],
    formality: "athletic",
    colorFamily: "grey",
  },
  {
    id: "m-w-boho-01",
    imageUrl: photo("m-w-boho-01"),
    genders: ["masculine"],
    eras: ["23_29", "30s", "40s"],
    archetypes: ["Boho"],
    label: "linen shirt + shorts",
    tasteTags: ["linen", "shorts", "coastal", "boho"],
    lifestyles: ["time_is_mine"],
    spend: ["best_value", "premium", "design_first"],
    formality: "casual",
    colorFamily: "sand",
  },
  {
    id: "m-w-bold-01",
    imageUrl: photo("m-w-bold-01"),
    genders: ["masculine"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Bold"],
    label: "statement jacket + tee",
    tasteTags: ["jacket", "tee", "bold", "edge"],
    lifestyles: [],
    spend: ["design_first", "premium"],
    formality: "casual",
    colorFamily: "black",
  },
  {
    id: "m-w-wild-01",
    imageUrl: photo("m-w-wild-01"),
    genders: ["masculine"],
    eras: [],
    archetypes: ["Wildcard"],
    label: "hoodie + jeans truth",
    tasteTags: ["hoodie", "jeans", "comfort", "real"],
    lifestyles: ["campus_life", "kids_in_the_mix", "time_is_mine"],
    spend: ["best_value", "deal_hunter"],
    formality: "casual",
    colorFamily: "grey",
  },

  // ── Masculine (elevated / dressier options in library) ────────────────────────────────────
  {
    id: "m-a-parisian-01",
    imageUrl: photo("m-a-parisian-01"),
    genders: ["masculine"],
    eras: ["23_29", "30s", "40s"],
    archetypes: ["Parisian"],
    label: "quiet-luxury travel",
    tasteTags: ["cashmere", "travel", "quiet-luxury", "parisian"],
    lifestyles: ["deep_in_career", "running_the_show"],
    spend: ["luxury", "premium"],
    formality: "smart",
    colorFamily: "cream",
  },
  {
    id: "m-a-minimal-01",
    imageUrl: photo("m-a-minimal-01"),
    genders: ["masculine", "androgynous"],
    eras: [],
    archetypes: ["Minimal"],
    label: "gallery black kit",
    tasteTags: ["gallery", "black", "minimal", "sculptural"],
    lifestyles: [],
    spend: ["luxury", "premium", "design_first"],
    formality: "formal",
    colorFamily: "black",
  },
  {
    id: "m-a-romantic-01",
    imageUrl: photo("m-a-romantic-01"),
    genders: ["masculine"],
    eras: ["23_29", "30s", "40s"],
    archetypes: ["Romantic"],
    label: "soft evening shirt",
    tasteTags: ["evening", "shirt", "soft", "romantic"],
    lifestyles: [],
    spend: ["premium", "luxury", "design_first"],
    formality: "formal",
    colorFamily: "ivory",
  },
  {
    id: "m-a-street-01",
    imageUrl: photo("m-a-street-01"),
    genders: ["masculine", "androgynous"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Street"],
    label: "street-sharp night",
    tasteTags: ["street", "leather", "sharp", "night"],
    lifestyles: [],
    spend: ["premium", "design_first", "luxury"],
    formality: "smart",
    colorFamily: "black",
  },
  {
    id: "m-a-classic-01",
    imageUrl: photo("m-a-classic-01"),
    genders: ["masculine"],
    eras: ["30s", "40s", "50s_60s", "65_plus"],
    archetypes: ["Classic"],
    label: "tailored suit day",
    tasteTags: ["suit", "tailored", "classic", "power"],
    lifestyles: ["deep_in_career", "running_the_show"],
    spend: ["luxury", "premium"],
    formality: "formal",
    colorFamily: "charcoal",
  },
  {
    id: "m-a-sporty-01",
    imageUrl: photo("m-a-sporty-01"),
    genders: ["masculine"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Sporty"],
    label: "clean athleisure set",
    tasteTags: ["athleisure", "clean", "sporty", "elevated"],
    lifestyles: [],
    spend: ["premium", "design_first", "best_value"],
    formality: "athletic",
    colorFamily: "cream",
  },
  {
    id: "m-a-boho-01",
    imageUrl: photo("m-a-boho-01"),
    genders: ["masculine"],
    eras: ["23_29", "30s", "40s"],
    archetypes: ["Boho"],
    label: "coastal linen set",
    tasteTags: ["linen", "coastal", "resort", "boho"],
    lifestyles: ["time_is_mine"],
    spend: ["premium", "design_first", "best_value"],
    formality: "casual",
    colorFamily: "sand",
  },
  {
    id: "m-a-bold-01",
    imageUrl: photo("m-a-bold-01"),
    genders: ["masculine"],
    eras: ["23_29", "30s", "40s"],
    archetypes: ["Bold"],
    label: "black-tie adjacent",
    tasteTags: ["dinner", "formal", "bold", "evening"],
    lifestyles: [],
    spend: ["luxury", "premium"],
    formality: "formal",
    colorFamily: "black",
  },
  {
    id: "m-a-wild-01",
    imageUrl: photo("m-a-wild-01"),
    genders: ["masculine"],
    eras: [],
    archetypes: ["Wildcard"],
    label: "architect coat moment",
    tasteTags: ["coat", "statement", "sculptural", "stretch"],
    lifestyles: [],
    spend: ["luxury", "design_first", "premium"],
    formality: "smart",
    colorFamily: "ivory",
  },

  // ── Androgynous / crossover extras for internal fallback depth ──
  {
    id: "x-w-street-02",
    imageUrl: photo("x-w-street-02"),
    genders: ["androgynous"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Street", "Bold"],
    label: "boxy denim layers",
    tasteTags: ["denim", "boxy", "street", "layers"],
    lifestyles: ["campus_life", "first_job"],
    spend: ["best_value", "design_first"],
    formality: "casual",
    colorFamily: "indigo",
  },
  {
    id: "x-w-minimal-02",
    imageUrl: photo("x-w-minimal-02"),
    genders: ["androgynous", "feminine", "masculine"],
    eras: [],
    archetypes: ["Minimal", "Classic"],
    label: "monochrome layers",
    tasteTags: ["monochrome", "layers", "minimal", "clean"],
    lifestyles: [],
    spend: ["premium", "design_first", "best_value"],
    formality: "smart",
    colorFamily: "grey",
  },
  {
    id: "x-w-sporty-02",
    imageUrl: photo("x-w-sporty-02"),
    genders: ["androgynous"],
    eras: [],
    archetypes: ["Sporty", "Wildcard"],
    label: "track pants + knit",
    tasteTags: ["track", "knit", "sporty", "comfort"],
    lifestyles: [],
    spend: ["best_value", "deal_hunter"],
    formality: "athletic",
    colorFamily: "grey",
  },
  {
    id: "x-a-classic-02",
    imageUrl: photo("x-a-classic-02"),
    genders: ["androgynous"],
    eras: ["30s", "40s", "50s_60s"],
    archetypes: ["Classic", "Parisian"],
    label: "sharp tailoring cut",
    tasteTags: ["tailored", "suit", "classic", "sharp"],
    lifestyles: ["deep_in_career", "running_the_show"],
    spend: ["luxury", "premium"],
    formality: "formal",
    colorFamily: "navy",
  },
  {
    id: "x-w-boho-02",
    imageUrl: photo("x-w-boho-02"),
    genders: ["feminine", "androgynous"],
    eras: ["23_29", "30s", "40s"],
    archetypes: ["Boho", "Romantic"],
    label: "easy earth layers",
    tasteTags: ["earth", "layers", "boho", "relaxed"],
    lifestyles: ["time_is_mine"],
    spend: ["best_value", "design_first"],
    formality: "casual",
    colorFamily: "earth",
  },
  {
    id: "x-a-bold-02",
    imageUrl: photo("x-a-bold-02"),
    genders: ["feminine", "androgynous"],
    eras: ["18_22", "23_29", "30s"],
    archetypes: ["Bold", "Wildcard"],
    label: "color-block statement",
    tasteTags: ["color-block", "statement", "bold", "print"],
    lifestyles: [],
    spend: ["design_first", "premium"],
    formality: "smart",
    colorFamily: "bright",
  },
  // Campus / younger eras
  {
    id: "f-w-street-campus",
    imageUrl: photo("f-w-street-campus"),
    genders: ["feminine"],
    eras: ["13_14", "15_17", "18_22"],
    archetypes: ["Street", "Wildcard"],
    label: "campus denim basics",
    tasteTags: ["denim", "campus", "casual", "street"],
    lifestyles: ["campus_life"],
    spend: ["best_value", "deal_hunter"],
    formality: "casual",
    colorFamily: "indigo",
  },
  {
    id: "m-w-street-campus",
    imageUrl: photo("m-w-street-campus"),
    genders: ["masculine"],
    eras: ["13_14", "15_17", "18_22"],
    archetypes: ["Street", "Sporty", "Wildcard"],
    label: "campus tee + jeans",
    tasteTags: ["tee", "jeans", "campus", "casual"],
    lifestyles: ["campus_life"],
    spend: ["best_value", "deal_hunter"],
    formality: "casual",
    colorFamily: "blue",
  },
  {
    id: "f-a-icon-refined",
    imageUrl: photo("f-a-icon-refined"),
    genders: ["feminine"],
    eras: ["50s_60s", "65_plus", "40s"],
    archetypes: ["Classic", "Parisian", "Minimal"],
    label: "refined cashmere day",
    tasteTags: ["cashmere", "refined", "classic", "quiet"],
    lifestyles: ["time_is_mine", "running_the_show"],
    spend: ["luxury", "premium"],
    formality: "smart",
    colorFamily: "cream",
  },
  {
    id: "m-a-icon-refined",
    imageUrl: photo("m-a-icon-refined"),
    genders: ["masculine"],
    eras: ["50s_60s", "65_plus", "40s"],
    archetypes: ["Classic", "Parisian"],
    label: "refined navy jacket",
    tasteTags: ["navy", "jacket", "refined", "classic"],
    lifestyles: ["time_is_mine", "running_the_show"],
    spend: ["luxury", "premium"],
    formality: "smart",
    colorFamily: "navy",
  },
];

export function getInhouseOutfitLooks(): readonly OutfitStyleLook[] {
  return INHOUSE_OUTFIT_LOOKS;
}
