/**
 * Deterministic, fast keyword → category detector.
 *
 * Used by:
 *  - the context builder to only inject relevant CategoryPreference /
 *    BrandPreference / TasteTag / HardNegative rows for the active query,
 *  - the gap detector to know which sizing field is needed (shoe vs top vs bottom).
 *
 * Returns canonical category names matching what the extractor / projector use.
 * If a query mentions multiple categories ("running shoes and a hoodie"), all
 * matches are returned.
 */

type CategoryRule = {
  category: string;
  /** Keywords (lowercase, word boundary matched). */
  keywords: string[];
};

const RULES: CategoryRule[] = [
  {
    category: "shoes",
    keywords: [
      "shoes",
      "shoe",
      "sneaker",
      "sneakers",
      "trainers",
      "running shoe",
      "running shoes",
      "runners",
      "boots",
      "boot",
      "loafer",
      "loafers",
      "sandal",
      "sandals",
      "heels",
      "high heels",
      "flats",
      "oxfords",
      "derbies",
      "mules",
      "espadrilles",
      "slippers",
      "footwear",
    ],
  },
  {
    category: "fashion",
    keywords: [
      "shirt",
      "shirts",
      "tee",
      "tees",
      "t-shirt",
      "tshirt",
      "t-shirts",
      "polo",
      "hoodie",
      "hoodies",
      "sweater",
      "sweaters",
      "jumper",
      "cardigan",
      "blazer",
      "jacket",
      "jackets",
      "coat",
      "coats",
      "pants",
      "trousers",
      "jeans",
      "denim",
      "shorts",
      "skirt",
      "skirts",
      "dress",
      "dresses",
      "suit",
      "suits",
      "outfit",
      "clothes",
      "clothing",
      "tracksuit",
      "outerwear",
      "underwear",
      "socks",
      "swimwear",
    ],
  },
  {
    category: "bags",
    keywords: [
      "bag",
      "bags",
      "backpack",
      "tote",
      "handbag",
      "duffel",
      "duffle",
      "weekender",
      "briefcase",
      "messenger bag",
      "crossbody",
      "shoulder bag",
      "clutch",
    ],
  },
  {
    category: "perfume",
    keywords: [
      "perfume",
      "fragrance",
      "cologne",
      "scent",
      "eau de parfum",
      "eau de toilette",
    ],
  },
  {
    category: "beauty",
    keywords: [
      "skincare",
      "moisturizer",
      "moisturiser",
      "serum",
      "cleanser",
      "sunscreen",
      "spf",
      "makeup",
      "lipstick",
      "mascara",
      "eyeliner",
      "concealer",
      "foundation",
      "shampoo",
      "conditioner",
      "haircare",
      "hair care",
    ],
  },
  {
    category: "tech",
    keywords: [
      "laptop",
      "macbook",
      "phone",
      "iphone",
      "android",
      "tablet",
      "ipad",
      "headphones",
      "earphones",
      "earbuds",
      "airpods",
      "monitor",
      "keyboard",
      "mouse",
      "camera",
      "gpu",
      "console",
      "ps5",
      "xbox",
      "switch",
      "smartwatch",
      "kindle",
      "speaker",
      "soundbar",
      "router",
    ],
  },
  {
    category: "watches",
    keywords: [
      "watch",
      "watches",
      "wristwatch",
      "smartwatch",
      "chronograph",
      "rolex",
      "omega",
      "seiko",
      "g-shock",
    ],
  },
  {
    category: "jewelry",
    keywords: [
      "jewelry",
      "jewellery",
      "ring",
      "rings",
      "necklace",
      "necklaces",
      "bracelet",
      "bracelets",
      "earrings",
      "earring",
      "pendant",
      "chain",
      "engagement ring",
      "wedding ring",
    ],
  },
  {
    category: "eyewear",
    keywords: [
      "sunglasses",
      "shades",
      "eyeglasses",
      "glasses",
      "spectacles",
      "frames",
      "ray-ban",
      "ray ban",
    ],
  },
  {
    category: "home",
    keywords: [
      "sofa",
      "couch",
      "chair",
      "office chair",
      "desk",
      "lamp",
      "rug",
      "carpet",
      "bedding",
      "sheets",
      "duvet",
      "pillow",
      "pillows",
      "curtains",
      "furniture",
      "kitchenware",
      "cookware",
      "knife",
      "pots",
      "blender",
      "coffee machine",
      "espresso machine",
      "vacuum",
      "decor",
      "decoration",
      "decorative",
      "desk decor",
      "home decor",
      "wall art",
      "plant pot",
      "candle",
      "candles",
      "vase",
      "shelf",
      "shelves",
      "bookshelf",
      "diffuser",
      "picture frame",
      "throw blanket",
      "desk organizer",
      "figurine",
      "statue",
    ],
  },
  {
    category: "fitness",
    keywords: [
      "gym",
      "fitness",
      "workout",
      "yoga",
      "yoga mat",
      "dumbbell",
      "dumbbells",
      "kettlebell",
      "running shoes",
      "treadmill",
      "bike",
      "bicycle",
      "cycling",
      "leggings",
      "sportswear",
      "activewear",
      "training",
      "boxing",
      "boxing gloves",
      "mma",
      "kickboxing",
      "jiu-jitsu",
      "jiujitsu",
      "martial arts",
      "punching bag",
      "speed bag",
      "sparring",
      "resistance band",
      "resistance bands",
      "pull-up bar",
      "jump rope",
      "foam roller",
      "weightlifting",
      "crossfit",
      "pilates",
    ],
  },
  {
    category: "supplements",
    keywords: [
      "supplement",
      "supplements",
      "vitamin",
      "vitamins",
      "protein powder",
      "whey protein",
      "whey",
      "creatine",
      "pre-workout",
      "preworkout",
      "pre workout",
      "bcaa",
      "amino acid",
      "amino acids",
      "collagen",
      "probiotics",
      "probiotic",
      "omega",
      "fish oil",
      "multivitamin",
      "multivitamins",
      "nootropic",
      "nootropics",
      "mass gainer",
      "protein bar",
      "protein bars",
      "energy drink",
      "electrolyte",
      "electrolytes",
      "magnesium",
      "zinc",
      "melatonin",
      "ashwagandha",
      "greens powder",
    ],
  },
  {
    category: "travel",
    keywords: [
      "luggage",
      "suitcase",
      "carry-on",
      "carry on",
      "travel adapter",
      "passport holder",
      "neck pillow",
    ],
  },
  {
    category: "gifts",
    keywords: [
      "gift",
      "gifts",
      "present",
      "presents",
      "anniversary gift",
      "birthday gift",
      "wedding gift",
    ],
  },
  {
    category: "baby",
    keywords: [
      "baby",
      "stroller",
      "diapers",
      "crib",
      "baby bottle",
      "pacifier",
      "infant",
    ],
  },
];

function containsToken(haystack: string, token: string): boolean {
  // Multi-word tokens: substring match is enough.
  if (token.includes(" ") || token.includes("-")) {
    return haystack.includes(token);
  }
  // Single-word: word-boundary match to avoid "shoe" matching "shoebill".
  const re = new RegExp(`\\b${token.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i");
  return re.test(haystack);
}

export function detectShoppingCategoryFromQuery(query: string): string[] {
  if (!query?.trim()) return [];
  const text = query.toLowerCase();
  const hits = new Set<string>();
  for (const rule of RULES) {
    for (const kw of rule.keywords) {
      if (containsToken(text, kw)) {
        hits.add(rule.category);
        break;
      }
    }
  }
  return [...hits];
}
