import {
  LEGAL_CONTACT_EMAIL,
  LEGAL_LAST_UPDATED,
  LEGAL_NAV,
  LEGAL_PATHS,
  type LegalSlug,
} from "./constants";

export type LegalDocument = {
  slug: LegalSlug;
  href: string;
  title: string;
  kick: string;
  description: string;
  lastUpdated: string;
  markdown: string;
};

const CONTACT = `[${LEGAL_CONTACT_EMAIL}](mailto:${LEGAL_CONTACT_EMAIL})`;

const TERMS: LegalDocument = {
  slug: "terms",
  href: LEGAL_PATHS.terms,
  title: "Terms of Service",
  kick: "The agreement",
  description:
    "The agreement between you and Shoop Inc. for using shoop.world.",
  lastUpdated: LEGAL_LAST_UPDATED,
  markdown: `
These terms are an agreement between you and Shoop Inc. ("Shoop", "we", "us"). They govern your use of shoop.world and everything on it. By creating an account you accept them.

We have tried to write these in plain language. Where a term is legally necessary but unusual, we explain why in the same paragraph.

## 1. What Shoop is

Shoop is a styling and shopping assistant. We analyze a photograph of your face that you provide, produce styling recommendations, render garments on a digital likeness of you, and connect you to retailers who sell those garments.

**Shoop does not sell clothing.** When you buy something, your contract is with the retailer, not with us.

**Shoop is currently available in the United States only.** We do not offer the service in, or target it to, other countries, and account creation from outside the US is not available.

## 2. Your account

- Provide accurate information and keep your password to yourself.
- You are responsible for activity on your account.
- One account per person. Do not create an account for someone else.
- Tell us promptly if you believe your account has been accessed without permission.

## 3. Age

**You must be at least 13 years old to use Shoop.** We ask your date of birth at signup and do not create accounts for anyone under 13. We do not knowingly process the photograph of anyone under 13. If we learn an account belongs to someone under 13, we will close it and delete all associated data, including face data, without waiting for a request.

## 4. Photographs you upload

Shoop works from a photograph of your face only. **We never ask for, and do not knowingly process, photographs of your body.** The characteristics used for fit are inferred, and you can view and correct them at any time in Settings.

You keep ownership of your photograph. You give us a limited licence to use it solely to operate the service for you: to derive measurements, to build your digital twin, to render garments on that twin, and to show those renders to people you choose to share them with. The photograph itself is deleted after extraction, as described in the [Biometric Data Consent and Policy](${LEGAL_PATHS.biometric}).

**We do not use your photograph to train artificial intelligence models.** We do not sell it. We do not license it to anyone for their own purposes. This commitment is repeated in the Privacy Policy and the Biometric Consent because we intend to be held to it.

You confirm that: the photograph is of you; you have the right to upload it; it does not contain any other identifiable person; it is not obscene, unlawful, or in breach of anyone's rights.

## 5. What we ask of you

Do not:

- Upload a photograph of anyone other than yourself.
- Use Shoop to harass, demean or comment on another person's appearance.
- Scrape, reverse engineer, or attempt to extract our models, measurements or rules.
- Resell or redistribute our styling output as your own service.
- Attempt to identify another user, or to re-identify anonymized data.
- Circumvent rate limits, access controls or link expiry.

We may suspend or close an account that breaches this section, and we will tell you why unless the law prevents us.

## 6. What our styling output is, and is not

**Shoop gives you an opinion.** It is generated by software from measurements derived from your photograph, and it is intended to be useful and honest. It is not a guarantee, and taste is not a fact.

**Our measurements are not a medical or health assessment.** We infer proportions and color values in order to recommend clothing. Nothing we produce is a diagnosis, a health opinion, or a statement about your body's condition, and it must not be relied on as one.

**Renders are illustrations, not photographs.** An image showing a garment on your digital twin is a computer-generated approximation. Color, drape, texture and fit will differ from the physical item. Always check the retailer's own sizing information before you buy.

**Availability and prices come from third parties** and change without notice. We show what we were told; we cannot promise it is current at the moment you click.

## 7. Commission

We earn a commission when you buy something through Shoop.

**Commission does not change what we tell you.** Our recommendation engine does not receive commission rates as an input, and it will recommend against a purchase where the honest answer is that the item does not work for you.

## 8. Subscriptions

Shoop does not sell a paid subscription. If we launch one, these terms will be updated first, and price, renewal, and cancellation will be shown on the subscribe screen before you pay.

## 9. Our intellectual property

Shoop, the Shoop name and logo, the software, the measurement engine, the rule set and the styling output are ours or our licensors'. You may use the service; you do not acquire rights in it.

You may share your own results — your palette, your looks, your renders — with friends or on social media. That is what they are for. The [Sharing and Community Policy](${LEGAL_PATHS.sharing}) governs how.

## 10. Ending the agreement

You can close your account at any time. When you do, we delete your biometric data first, promptly, in accordance with the Biometric Consent, and the rest of your data in accordance with the Privacy Policy.

We may suspend or close your account if you breach these terms, if we are required to by law, or if we discontinue the service. If we discontinue the service we will give you reasonable notice and a way to export your data.

## 11. Changes

We may update these terms. If a change materially affects your rights we will give you at least 30 days' notice by email and in the product before it takes effect. Continuing to use Shoop after that means you accept the change.

**We will never apply a change to the biometric consent retroactively.** If we want to do something new with your biometric data, we will ask you again.

## 12. Liability

We provide Shoop with reasonable care and skill. We do not promise it will be uninterrupted, error-free, or that its recommendations will suit you.

To the maximum extent the law allows, we are not liable for indirect or consequential loss, and our total liability to you in any twelve-month period is limited to the greater of the amounts you paid us in that period and USD 100.

**Nothing in these terms limits liability that cannot lawfully be limited,** including liability for death or personal injury caused by negligence, for fraud, or for any consumer right that your state does not allow to be excluded. Some states do not allow the exclusion of certain warranties or damages; where that is so, the exclusion does not apply to you.

## 13. Disputes: arbitration and class waiver

**Please read this section. It affects how disputes between us are resolved.**

Before any formal proceeding, you agree to email us at ${CONTACT} describing the dispute, and both of us will try in good faith to resolve it within 60 days.

If we cannot, **any dispute between you and Shoop will be resolved by binding individual arbitration** under the Federal Arbitration Act, administered by the American Arbitration Association under its Consumer Arbitration Rules, with hearings conducted remotely or in the county where you live. These terms are governed by the laws of Delaware.

**Class waiver.** Disputes are resolved individually. Neither of us may bring or participate in a class, collective or representative action against the other.

**Your opt-out right.** You may reject this arbitration section entirely by emailing ${CONTACT} within 30 days of creating your account, with the subject line "arbitration opt-out". Opting out does not affect any other part of these terms.

**Small claims.** Either of us may bring an individual claim in small-claims court instead of arbitration.

**Coordinated filings.** If 25 or more similar arbitration demands are filed against Shoop by the same or coordinated counsel, the demands will be resolved in staged batches: the parties will each select up to 10 demands to proceed first as bellwethers, and remaining demands are stayed, with filing fees due only as each batch proceeds. If this paragraph is found unenforceable, the affected demands proceed in arbitration individually.

If the law of your jurisdiction does not permit mandatory arbitration or class waivers, this section does not apply to you and disputes will be resolved in the courts of your home jurisdiction.

## 14. Contact

${CONTACT} · Shoop Inc., United States
`.trim(),
};

const PRIVACY: LegalDocument = {
  slug: "privacy",
  href: LEGAL_PATHS.privacy,
  title: "Privacy Policy",
  kick: "What we hold",
  description:
    "What we collect, why, how long we keep it, and the controls you have.",
  lastUpdated: LEGAL_LAST_UPDATED,
  markdown: `
This explains what we collect, why, how long we keep it, and what you can do about it. Biometric data is covered in more detail in the separate [Biometric Data Consent and Policy](${LEGAL_PATHS.biometric}), which you must accept before any photograph is processed.

The short version: **we work from one photograph of your face, we never ask for photographs of your body, we delete your photograph after we've measured what we need, we keep numbers rather than images, and we never sell your data to anyone.**

## 1. Who we are

Shoop Inc., United States, is the controller of your personal data. Contact: ${CONTACT}.

Shoop serves the United States only and does not create accounts from the EU or UK.

## 2. What we collect

| Category | Examples | Why |
| --- | --- | --- |
| Account | Name, email, date of birth, password hash | To give you an account and enforce the age gate |
| Questionnaire | Height, comfort constraints, climate, style preferences, occasions | To recommend clothing that fits your life |
| Photograph | One face photo | To measure you and build your digital twin. Deleted after extraction. |
| Derived measurements | Color values and proportions, each with a confidence value | To generate styling. Covered by the Biometric Consent. You can view and correct these in Settings. |
| Renders | Images of your digital twin wearing garments | To show you how something looks before you buy |
| Activity | Items viewed, verdicts shown, reactions, saved looks, friend votes sent and received, purchases completed | To improve what we show you, and to measure whether our advice is any good |
| Transactions | Orders placed through Shoop | To operate the service and account for commission |
| Technical | IP address, device and browser type, approximate location | Security, fraud prevention, and enforcing the regions where Shoop is available |

**We never ask for a photograph of your body.** Body characteristics used for fit are inferred and correctable. **Weight is optional and is used only for sizing;** it is not used by any styling recommendation, and the product works without it.

## 3. Where the processing happens

**Processing is server-side.** Your photograph is uploaded to our infrastructure and analyzed there to derive your measurements and create your digital twin. **The source photograph is deleted once extraction completes, and in any event within 24 hours of upload.** What persists afterward is the derived numbers and your twin — no photograph, and no face template.

## 4. What we do not do

- We do not use your photograph or measurements to train artificial intelligence models.
- We do not sell your personal data, and we have not sold it in the preceding 12 months. We do not share it with advertisers.
- We do not use your data to target advertising to you anywhere.
- We do not show your data to other users except where you deliberately share a look.
- We do not use your photograph or any derived data to identify you or anyone else, and we do not operate or contribute to any facial-recognition system.

## 5. Who we share with

| Recipient | What they receive | Why |
| --- | --- | --- |
| **FASHN** (render provider) | Your photograph (as image bytes) and a garment image, for the duration of the render. FASHN's public API has no deletion call we can invoke. They publish that CDN outputs expire after three days. Request records may remain in their dashboard. We delete our copies of the photograph, twin, and renders. | To generate the try-on render |
| **OpenAI** | Your photograph during extraction | To derive measurements |
| **Anthropic** | Your derived numbers and preferences during styling | To produce styling output |
| Cloud hosting (**Railway**) | Encrypted data at rest | To run the service |
| Checkout partners and payment processors | Order and payment details, which we never see in full | To complete purchases you choose to make |
| Retailers | Order details when you buy — never your photograph, never your measurements | To fulfil your order |
| People you share with | The specific look you sent, and your first name | Because you chose to send it |

We instruct processors to delete data where their contract and API allow it. FASHN does not offer a deletion API; we delete our copies and rely on their published three-day CDN expiry for theirs. Users are in the US and production infrastructure is hosted in the US.

## 6. How long we keep things

| Data | Retention |
| --- | --- |
| Source face photograph | Deleted after extraction, at most 24 hours |
| Derived measurements and twin | Deleted on your request, on account closure, or 3 years after your last interaction with Shoop — whichever comes first |
| Account and questionnaire | Until you close your account, then deleted |
| Renders | Until you delete them or close your account |
| Shared links | 7 days from creation, then permanently unavailable |
| Transactions | 7 years, as required for tax and accounting |
| Technical logs | 12 months |

## 7. Your rights

Wherever you live in the US, we give you the same controls: see what we hold, correct anything that is wrong (including every inferred measurement, in Settings), delete your data, get a copy in a portable format, and withdraw consent — including biometric consent — at any time. California residents: these are your CCPA rights, honored for everyone; we do not sell or share personal information as the CCPA defines those terms, and we will never treat you worse for exercising a right.

Email ${CONTACT}. We respond within 30 days, free. You can also use the Data & privacy controls in Settings.

## 8. Security

Encryption in transit and at rest. Access limited to staff who need it, logged and reviewed. Share links are unguessable, expire, and are excluded from search indexing. We will notify you and the relevant regulator of a breach affecting your data within the period the law requires, and faster if we can.

## 9. Children

**Shoop is for users 13 and older.** We ask date of birth at signup and do not knowingly collect data from anyone under 13. If we discover that we have, we delete it, including any biometric data, without waiting for a request. Report a suspected under-13 account to ${CONTACT}.

## 10. Where Shoop is available

The United States. Account creation from the EU and UK is not available, and we do not target the service there. If that changes, this policy is updated first, including the additional rights that apply in those regions.

## 11. Changes

We tell you before any material change, and we never apply a change to biometric processing retroactively.
`.trim(),
};

const BIOMETRIC: LegalDocument = {
  slug: "biometric",
  href: LEGAL_PATHS.biometric,
  title: "Biometric Data Consent and Policy",
  kick: "A separate consent",
  description:
    "Written notice and release before any face photograph is processed, including retention and destruction.",
  lastUpdated: LEGAL_LAST_UPDATED,
  markdown: `
This is a separate consent. It is presented on its own screen, immediately before the photo upload control, and must be accepted by an affirmative act before any photograph is processed. It is not bundled into the Terms of Service, and acceptance of the Terms does not constitute acceptance of this. This page also serves as our publicly available retention schedule and destruction guidelines.

## 1. What we are asking

To style you, Shoop needs to measure you. It does that from one photograph of your face.

We are asking your permission to derive numerical measurements from that photograph. In some places the law calls this biometric information and treats it as sensitive. We agree that it is, which is why this is a separate page and not a line in a long document.

**We never ask for a photograph of your body.** Body characteristics used for fit are inferred from your face photograph and your questionnaire answers, and you can view and correct every one of them in Settings.

## 2. Exactly what we derive

From your face photograph:

- Color values of your skin, hair and eyes
- Facial and neck proportions
- Inferred body proportions used for fit — shoulder to hip, torso to leg, and similar — expressed as numbers with a confidence value, and correctable by you

**We do not create or store a faceprint, a face template, or any identifier capable of recognizing you in another photograph.** We do not perform facial recognition. We do not estimate your age, gender, ethnicity, emotional state, or health. Height comes from what you tell us; weight is optional and used only for sizing.

## 3. Why we need it

For one purpose only: to recommend clothing that suits you, and to render garments on your digital twin so you can see them before you buy.

**We will not use it for anything else without asking you again.** If we ever want to, we will come back with a new consent, and you will be free to say no and keep using the service as before.

## 4. Where your photograph goes, by name

Your photograph is uploaded to our servers and processed there. Two named providers touch it:

- **OpenAI** — analyzes the photograph to derive the measurements above
- **FASHN** — renders garments on your digital twin

**Your photograph is deleted from our systems once extraction and twin creation are complete, and in any event within 24 hours of upload.** What persists is the derived numbers and your twin.

FASHN's public API has no deletion instruction we can call or verify. Their documentation states that CDN-delivered outputs expire after three days, and request history may remain in their dashboard. We delete our copies immediately. OpenAI receives the photograph only for the extraction request.

## 5. What this is not

**This is not a health assessment.** We derive proportions in order to recommend clothing. Nothing we produce is a medical opinion.

**This is not a rating of you.** Shoop scores garments and outfits. It does not score, rank or rate a person, and it is built so that it cannot.

## 6. Retention schedule and destruction guidelines

| What | Destroyed |
| --- | --- |
| Your photograph | On completion of extraction, at most 24 hours after upload |
| Derived measurements | On your deletion request, on withdrawal of this consent, on account closure, or **3 years after your last interaction with Shoop** — whichever comes first |
| Your twin and renders | The same |

**Deletion is permanent.** When a trigger occurs, we destroy the measurements, twin and renders in our systems. FASHN does not expose a deletion API; their published CDN retention is three days. We keep no copy for training, research, or anything else. An automated job enforces the 3-year trigger without waiting for a request. Each automated or requested deletion is logged with a timestamp.

## 7. Who else sees it

The named providers in section 4, for the purposes stated. Nobody else. We do not sell, lease, trade, or disclose your biometric information for anyone's commercial benefit, and we do not use it to train any model, ours or anyone else's. This is a permanent commitment.

## 8. Withdrawing

Withdraw at any time in Settings or by emailing ${CONTACT}. When you do: your measurements, twin and renders are deleted; your account stays open; you can keep using Shoop with questionnaire answers alone.

**Withdrawing costs you the twin. It does not cost you the account.**

## 9. Your acknowledgement

By ticking the box in the product you confirm:

1. You have read this document.
2. You are at least 13 years old.
3. The photograph is of you and you have the right to upload it.
4. You permit Shoop Inc. to collect, store and use biometric information as described here, for the purpose described here, for the period described here, including processing by the named providers in section 4.
5. You understand you can withdraw at any time.

The box is not pre-ticked, is not bundled with any other consent, and is presented before the upload control is enabled. The tick is logged with timestamp, document version and user id.
`.trim(),
};

const SHARING: LegalDocument = {
  slug: "sharing",
  href: LEGAL_PATHS.sharing,
  title: "Sharing and Community Policy",
  kick: "Looks you send",
  description:
    "What happens when you send a look to friends and ask them to vote.",
  lastUpdated: LEGAL_LAST_UPDATED,
  markdown: `
Shoop lets you send a look to friends and ask them to vote. This page covers what happens when you do.

## 1. What gets shared

When you send a look, the people you send it to can see: the rendered image of your digital twin wearing the outfits; your first name; the garments in each look. They cannot see your measurements, your questionnaire answers, your other looks, or anything else about your account.

**A render shows your likeness.** Only send it to people you would be comfortable showing a photograph of yourself.

## 2. Your consent at the point of sharing

Sharing a photorealistic render of you with people outside the service requires its own consent:

- **First share:** a one-time screen: "You're about to send a realistic image of you to people you choose. They don't need an account to see it. The link expires in 7 days and you can revoke it any time." Affirmative confirmation, logged.
- **Every share:** the send screen states who can see it and when the link dies. Sharing is always initiated by you; Shoop never shares a render on its own.

## 3. How the link works

Long and unguessable, listed nowhere; expires after 7 days; revocable by you at any time from your account; excluded from search indexing; recipients need no account and we create none for them.

**We cannot prevent someone screenshotting what you send them.** No link-based sharing can. Send it to people you trust.

## 4. Recipients

If you are voting: someone asked your opinion on clothes — that is the whole scope. Do not screenshot and redistribute what you were sent. Do not comment on the person's body; the question is about the garment. Do not use the link for anything other than voting.

## 5. What we record about a vote

The option chosen, an optional short reason, and the first name the voter enters. Used to show the result and improve recommendations. Voters are not tracked, no profile is built for them, and no cookie beyond the strictly necessary is set on the voting page.

## 6. Reporting and enforcement

If a Shoop link is used to harass you, or an image of you is shared without your permission, email ${CONTACT}. We disable the link immediately, before we investigate anything else. We may disable links, suspend or close accounts that breach this policy, and where the law requires, report to the appropriate authority.
`.trim(),
};

const COOKIES: LegalDocument = {
  slug: "cookies",
  href: LEGAL_PATHS.cookies,
  title: "Cookie Policy",
  kick: "A small number",
  description: "Every cookie we use, and how to manage the ones you can refuse.",
  lastUpdated: LEGAL_LAST_UPDATED,
  markdown: `
We use a small number of cookies. Here is all of them.

| Type | Set by | What for | Can you refuse? |
| --- | --- | --- | --- |
| Essential | Shoop | Keeping you logged in, security, remembering your cart, remembering this cookie choice | No — the service does not work without them |
| Preferences | — | Region and display settings. A toggle is ready in Settings. We do not currently set a preference cookie. | Yes |
| Analytics | — | Understanding which parts of the product are used. A toggle is ready in the first-visit banner and in Settings. We do not currently set an analytics cookie. | Yes |
| Affiliate attribution | Not set by Shoop. When you follow a product link, the retailer or their network may set cookies on *their* site. We have not confirmed a named affiliate network. | So a retailer can attribute a visit that started on Shoop | Governed by the retailer's own cookie controls; following a link out of Shoop is the action that triggers it |
| Advertising | — | None. We do not run advertising cookies and we do not permit cross-site tracking from our pages. | — |

Manage non-essential cookies from the first-visit banner and any time afterwards in Settings.
`.trim(),
};

export const LEGAL_DOCUMENTS: Record<LegalSlug, LegalDocument> = {
  terms: TERMS,
  privacy: PRIVACY,
  biometric: BIOMETRIC,
  sharing: SHARING,
  cookies: COOKIES,
};

export function legalDocument(slug: LegalSlug): LegalDocument {
  return LEGAL_DOCUMENTS[slug];
}

export function legalNavFor(slug: LegalSlug) {
  return LEGAL_NAV.map((item) => ({
    ...item,
    current: item.slug === slug,
  }));
}
